Repository Health-Food-Me/Health-Food-Me-Server, pull requests merged in 2022-09, with the labels that each got.

#303 Feature/#302
  .github/workflows/deploy.yml
  appspec.yml
  scripts/after-deploy.sh
  src/controllers/ReviewController.ts
  src/routes/ReviewRouter.ts
  src/services/ReviewService.ts
  src/services/UserService.ts
Labels: 🍋 SEOWOO

#304 Feature/#289 회원 탈퇴 재수정
  src/services/ReviewService.ts
  src/services/UserService.ts
Labels: 🍋 SEOWOO

#309 Feature/#305
  src/controllers/RestaurantController.ts
  src/controllers/ReviewController.ts
  src/controllers/UserController.ts
  src/routes/ReviewRouter.ts
  src/routes/UserRouter.ts
Labels: 🍋 SEOWOO

#308 Feature/#306
  src/controllers/RestaurantController.ts
  src/controllers/ReviewController.ts
  src/controllers/TokenController.ts
  src/controllers/UserController.ts
  src/interface/restaurant/AroundRestaurant.ts
  src/interface/restaurant/AutoCompleteSearch.ts
  src/interface/restaurant/Menu.ts
  src/interface/restaurant/MenuData.ts
  src/interface/restaurant/Prescription.ts
  src/interface/restaurant/PrescriptionResponse.ts
  src/interface/restaurant/Query.ts
  src/interface/restaurant/Restaurant.ts
  src/interface/restaurant/ScrapData.ts
  src/interface/review/GetReviews.ts
  src/interface/user/User.ts
  src/interface/user/UserProfile.ts
  src/models/Menu.ts
  src/models/Prescription.ts
  src/models/Restaurant.ts
  src/modules/exceptionMessage.ts
  src/modules/responseMessage.ts
  src/routes/AuthRouter.ts
  src/routes/ReviewRouter.ts
  src/services/RestaurantService.ts
  src/services/ReviewService.ts
  src/services/UserService.ts
Labels: ✅ TEST, 🐞 FIX, 🐣SOHYEON

#312 [feature/#311] FIX: 쿼리 및 카테고리 변경된 타입 반영
  src/interface/restaurant/Query.ts
  src/services/RestaurantService.ts
Labels: 🐣SOHYEON

#318 [feature/#317] FIX: 예외처리 추가 및 데이터 타겟 변경
  src/services/ReviewService.ts
Labels: 🐣SOHYEON
