Repository Health-Food-Me/Health-Food-Me-Server, pull requests merged in 2022-07, with the labels that each got.

#8 [feature/#6] Sentry 활용하여 에러 수집/성능 모니터링
  .gitignore
  package.json
  src/config/index.ts
  src/index.ts
  yarn.lock
Labels: ⚙ CHORE, ☃️ NUNU

#9 [feature/#7] Mongoose config 방법 변경
  src/config/mongooseConfig.ts
  src/index.ts
  src/loaders/db.ts
Labels: ⚙ CHORE, ☃️ NUNU

#11 [feature/#10] dependabot.yml 설정
  .github/dependabot.yml
Labels: ⚙ CHORE, ☃️ NUNU

#21 [feature/#17] Test 환경 설정 및 Template Engine 설정
  jest.config.js
  package.json
  src/index.ts
  src/test/sample.test.ts
  yarn.lock
Labels: ⚙ CHORE, ☃️ NUNU

#22 [feature/#5] 소셜 로그인 구현
  package.json
  src/config/auth.ts
  src/config/index.ts
  src/controllers/UserController.ts
  src/controllers/index.ts
  src/interfaces/SocialUserInfo.ts
  src/interfaces/UserInfo.ts
  src/models/User.ts
  src/modules/exceptionMessage.ts
  src/modules/jwtHandler.ts
  src/modules/responseMessage.ts
  src/routes/AuthRouter.ts
  src/routes/index.ts
  src/services/SocialAuthStrategy.ts
  src/services/UserService.ts
  src/services/index.ts
Labels: ✨ FEATURE

#26 [feature/#18] DB 스키마 + 도메인 엔티티 메이킹
  .eslintrc.json
  .github/workflows/deploy.yml
  src/controllers/UserController.ts
  src/interface/Category.ts
  src/interface/Menu.ts
  src/interface/Nutrient.ts
  src/interface/Prescription.ts
  src/interface/Restaurant.ts
  src/interface/Review.ts
  src/interface/SocialUser.ts
  src/interface/User.ts
  src/models/Category.ts
  src/models/Menu.ts
  src/models/Model.ts
  src/models/Nutrient.ts
  src/models/Prescription.ts
  src/models/Review.ts
  src/models/User.ts
  src/models/restaurant.ts
  src/routes/AuthRouter.ts
Labels: ✨ FEATURE, ☃️ NUNU

#38 [feature/#37] 빌드 스크립트 & 에러 수정
  .github/workflows/deploy.yml
  dist/config/auth.js
  dist/config/auth.js.map
  dist/config/index.js
  dist/config/index.js.map
  dist/config/mongooseConfig.js
  dist/config/mongooseConfig.js.map
  dist/config/multerConfig.js
  dist/config/multerConfig.js.map
  dist/config/s3Config.js
  dist/config/s3Config.js.map
  dist/config/winstonConfig.js
  dist/config/winstonConfig.js.map
  dist/controllers/TokenController.js
  dist/controllers/TokenController.js.map
  dist/controllers/UserController.js
  dist/controllers/UserController.js.map
  dist/controllers/index.js
  dist/controllers/index.js.map
  dist/index.js
  dist/index.js.map
  dist/interfaces/SocialUserInfo.js
  dist/interfaces/SocialUserInfo.js.map
  dist/interfaces/UserInfo.js
  dist/interfaces/UserInfo.js.map
  dist/models/User.js
  dist/models/User.js.map
  dist/modules/BaseResponse.js
  dist/modules/BaseResponse.js.map
  dist/modules/exceptionMessage.js
  dist/modules/exceptionMessage.js.map
  dist/modules/jwtHandler.js
  dist/modules/jwtHandler.js.map
  dist/modules/responseMessage.js
  dist/modules/responseMessage.js.map
  dist/modules/statusCode.js
  dist/modules/statusCode.js.map
  dist/routes/AuthRouter.js
  dist/routes/AuthRouter.js.map
  dist/routes/index.js
  dist/routes/index.js.map
  dist/services/SocialAuthStrategy.js
  dist/services/SocialAuthStrategy.js.map
  dist/services/UserService.js
  dist/services/UserService.js.map
  dist/services/index.js
  dist/services/index.js.map
  dist/test/sample.test.js
  dist/test/sample.test.js.map
  package.json
  src/config/auth.ts
Labels: 🐞 FIX, ☃️ NUNU

#46 [feature/#45] README 수정
  README.md
  package.json
Labels: 📃 DOCS, ☃️ NUNU

#53 [feature/#36] 메인 지도 식당 조회 API 구현
  .gitignore
  src/controllers/RestaurantController.ts
  src/controllers/UserController.ts
  src/controllers/dto/restaurant/AroundRestaurantDto.ts
  src/interface/Category.ts
  src/interface/Restaurant.ts
  src/models/Category.ts
  src/models/restaurant.ts
  src/modules/responseMessage.ts
  src/routes/RestaurantRouter.ts
  src/services/RestaurantService.ts
Labels: ✨ FEATURE, ☃️ NUNU

#47 [feature/#44] 메뉴 상세 정보 조회
  src/controllers/RestaurantController.ts
  src/interface/MenuData.ts
  src/interface/Restaurant.ts
  src/modules/responseMessage.ts
  src/routes/RestaurantRouter.ts
  src/services/RestaurantService.ts
Labels: ✨ FEATURE, 🐣SOHYEON

#63 [Feature/#59] 리팩토링(+populate) 및 예외처리 추가
  src/controllers/RestaurantController.ts
  src/controllers/UserController.ts
  src/interface/Category.ts
  src/interface/Prescription.ts
  src/models/Category.ts
  src/services/RestaurantService.ts
  src/services/UserService.ts
Labels: 🔨 REFACTOR, 🐣SOHYEON

#86 [feature/#60] 식당 자동 검색 기능 구현
  src/controllers/RestaurantController.ts
  src/controllers/dto/restaurant/AutoCompleteSearchDto.ts
  src/modules/responseMessage.ts
  src/routes/RestaurantRouter.ts
  src/services/RestaurantService.ts
Labels: ✨ FEATURE, ☃️ NUNU

#93 [feature/#87] 식당 리뷰 조회 API
  src/controllers/ReviewController.ts
  src/controllers/dto/review/GetReviewsDto.ts
  src/controllers/index.ts
  src/interface/Review.ts
  src/interface/User.ts
  src/models/Review.ts
  src/modules/responseMessage.ts
  src/routes/ReviewRouter.ts
  src/routes/index.ts
  src/services/ReviewService.ts
  src/services/index.ts
Labels: ✨ FEATURE, ☃️ NUNU

#96 [feature/#95] 유저당 리뷰 API 구현
  src/controllers/ReviewController.ts
  src/interface/Review.ts
  src/modules/responseMessage.ts
  src/routes/ReviewRouter.ts
  src/services/ReviewService.ts
Labels: ✨ FEATURE, ☃️ NUNU

#98 [feature/#97] 리뷰 삭제 API 구현
  src/controllers/ReviewController.ts
  src/controllers/UserController.ts
  src/controllers/dto/review/GetReviewsDto.ts
  src/modules/responseMessage.ts
  src/routes/ReviewRouter.ts
  src/services/ReviewService.ts
Labels: ✨ FEATURE, ☃️ NUNU

#100 [feature/#99] 네이버 블로그 리뷰 API 구현
  src/config/index.ts
  src/controllers/ReviewController.ts
  src/interface/Review.ts
  src/modules/responseMessage.ts
  src/routes/ReviewRouter.ts
  src/services/RestaurantService.ts
  src/services/ReviewService.ts
Labels: ✨ FEATURE, ☃️ NUNU

#113 [feature/#112] Auth Router쪽 API 문서화
  swaggerJson.json
Labels: 📃 DOCS, ☃️ NUNU

#141 [feature/#140] categoryId -> categoryName 수정
  .DS_Store
  src/controllers/RestaurantController.ts
  src/services/RestaurantService.ts
  swaggerJson.json
Labels: 🐞 FIX, ☃️ NUNU

#143 [feature/#142] 스크랩 식당 최신화시켜주기 위한 API 변경
  src/controllers/UserController.ts
  src/interface/UserProfile.ts
  src/routes/UserRouter.ts
  src/services/UserService.ts
Labels: 🐞 FIX, ☃️ NUNU

#144 [feature/#142] 누락된 scrapRestaurants 추가
  src/services/UserService.ts
Labels: 🐞 FIX, ☃️ NUNU

#147 [feature/#146] Husky 활용하여 commit 전에 lint fix하여 커밋할 수 있게 설정
  .husky/pre-commit
  package.json
  yarn.lock
Labels: 🌏 DEPLOY, ☃️ NUNU

#149 [feature/#148] Production에서만 1시간 유효기간 설정
  src/modules/jwtHandler.ts
Labels: 🐞 FIX, ☃️ NUNU

#154 [feature/#153] 리뷰 삭제 로직 변경
  src/controllers/ReviewController.ts
  src/interface/UserProfile.ts
  src/services/RestaurantService.ts
  src/services/ReviewService.ts
Labels: 🐞 FIX, ☃️ NUNU

#156 [HOTFIX] params에 안 지운 오타 수정
  src/controllers/ReviewController.ts
Labels: 🐞 FIX, ☃️ NUNU

#157 리뷰 Delete router 변경
  src/routes/ReviewRouter.ts
Labels: 🐞 FIX, ☃️ NUNU

#171 [feature/fix_error] 메뉴/메인지도 API 부분 수정
  src/services/RestaurantService.ts
Labels: 🐞 FIX, ☃️ NUNU

#187 [feature/#186] Husky test
  .husky/pre-commit
  package.json
  src/services/RestaurantService.ts
  src/services/UserService.ts
  yarn.lock
Labels: ☃️ NUNU
